# Generated by Django 3.1 on 2022-02-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdata',
            name='dog_chbox',
            field=models.BooleanField(blank=True, default=False, verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='childdata',
            name='personal_number',
            field=models.CharField(default='', max_length=15, verbose_name='Номер личного дела'),
        ),
        migrations.AlterField(
            model_name='childdata',
            name='sex',
            field=models.CharField(choices=[('boy', 'М'), ('girl', 'Ж')], default='Пол не выбран', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='childdata',
            name='teach_status',
            field=models.CharField(choices=[('free', 'Бюджет'), ('pay', 'Платник')], default='---', max_length=20, verbose_name='Тип обучения'),
        ),
    ]
