# Generated by Django 3.1 on 2022-02-27 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbs_app', '0002_auto_20220228_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childdata',
            old_name='dog_chbox',
            new_name='dog_checkbox',
        ),
    ]
