# Generated by Django 3.1 on 2022-02-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs_app', '0003_auto_20220228_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childdata',
            old_name='dog_checkbox',
            new_name='doc_dogovor_checkbox',
        ),
        migrations.AddField(
            model_name='childdata',
            name='doc_opd_checkbox',
            field=models.BooleanField(blank=True, default=False, verbose_name='Согласие на ОПД'),
        ),
        migrations.AddField(
            model_name='childdata',
            name='doc_soprovod_checkbox',
            field=models.BooleanField(blank=True, default=False, verbose_name='Заявление о сопровождени (до 12 лет)'),
        ),
        migrations.AddField(
            model_name='childdata',
            name='doc_svid_checkbox',
            field=models.BooleanField(blank=True, default=False, verbose_name='Копия св-ва о рождении'),
        ),
        migrations.AddField(
            model_name='childdata',
            name='doc_zayavl_checkbox',
            field=models.BooleanField(blank=True, default=False, verbose_name='Заявление'),
        ),
    ]
