# Generated by Django 3.1 on 2020-08-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs_app', '0003_auto_20200806_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childdata',
            options={'verbose_name': 'Ребёнок', 'verbose_name_plural': 'Дети'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Объединение', 'verbose_name_plural': 'Объединения'},
        ),
        migrations.AlterModelOptions(
            name='teacherdata',
            options={'verbose_name': 'Педагог', 'verbose_name_plural': 'Педагоги'},
        ),
        migrations.RenameField(
            model_name='childdata',
            old_name='midlle_name',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='teacherdata',
            old_name='midlle_name',
            new_name='middle_name',
        ),
        migrations.AlterField(
            model_name='childdata',
            name='date_birth',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='date_birth',
            field=models.DateField(verbose_name='Date of birth'),
        ),
    ]
