# Generated by Django 3.1 on 2022-02-28 00:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dbs_app', '0004_auto_20220228_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdata',
            name='udo_group',
            field=models.CharField(blank=True, default='---', max_length=20, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='childdata',
            name='family_status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('status1', 'Малообеспеченная семья'), ('status2', 'Многодетная семья'), ('status3', 'Сирота'), ('status4', 'Под опекой'), ('status5', 'ОВЗ'), ('status6', 'Инвалид')], max_length=47, verbose_name='Семейный статус'),
        ),
    ]
