# Generated by Django 3.1 on 2020-08-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs_app', '0004_auto_20200813_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childdata',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AddField(
            model_name='childdata',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='childdata',
            name='sex',
            field=models.CharField(blank=True, choices=[('М', 'boy'), ('Ж', 'girl')], max_length=2, null=True),
        ),
    ]
