# Generated by Django 3.1 on 2020-08-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs_app', '0006_auto_20200813_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdata',
            name='sex',
            field=models.CharField(blank=True, choices=[('boy', 'М'), ('girl', 'Ж')], default='Выберите пол', max_length=10),
        ),
    ]
