# Generated by Django 3.1 on 2020-08-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs_app', '0007_auto_20200813_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdata',
            name='sex',
            field=models.CharField(blank=True, choices=[('boy', 'М'), ('girl', 'Ж')], default='Sex is not set', max_length=10),
        ),
    ]
