# Generated by Django 3.1 on 2020-08-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs_app', '0008_auto_20200813_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdata',
            name='class_number',
            field=models.CharField(blank=True, default='---', max_length=50, null=True, verbose_name='№ класса'),
        ),
        migrations.AddField(
            model_name='childdata',
            name='diagnose',
            field=models.CharField(blank=True, default='---', max_length=100, verbose_name='Диагноз (если выбран статус "ОВЗ" или "Инвалид"'),
        ),
        migrations.AddField(
            model_name='childdata',
            name='family_status',
            field=models.CharField(blank=True, choices=[('status1', 'Малообеспеченная семья'), ('status2', 'Многодетная семья'), ('status3', 'Сирота'), ('status4', 'Под опекой'), ('status5', 'ОВЗ'), ('status6', 'Инвалид')], default='status0', max_length=10, verbose_name='Семейный статус'),
        ),
        migrations.AddField(
            model_name='childdata',
            name='he_name',
            field=models.CharField(blank=True, default='---', max_length=50, null=True, verbose_name='Название учреждения ВО'),
        ),
        migrations.AddField(
            model_name='childdata',
            name='he_number',
            field=models.CharField(blank=True, default='---', max_length=50, null=True, verbose_name='№ курса'),
        ),
        migrations.AddField(
            model_name='childdata',
            name='municipal_name',
            field=models.CharField(blank=True, default='---', max_length=50, null=True, verbose_name='Название МООУ'),
        ),
        migrations.AddField(
            model_name='childdata',
            name='municipal_status',
            field=models.CharField(blank=True, choices=[('Yes', 'Посещающий'), ('No', 'Семейное обучение')], max_length=20, null=True, verbose_name='Посещение МООУ'),
        ),
        migrations.AddField(
            model_name='childdata',
            name='special_status',
            field=models.CharField(choices=[('no_spec', 'Не состоит'), ('ooy_spec', 'Состоит в ООУ'), ('pdn_spec', 'Состоит в ПДН')], default='no_spec', max_length=10, verbose_name='Состоит на учёте?'),
        ),
        migrations.AddField(
            model_name='childdata',
            name='spo_name',
            field=models.CharField(blank=True, default='---', max_length=50, null=True, verbose_name='Название СПО'),
        ),
        migrations.AddField(
            model_name='childdata',
            name='spo_number',
            field=models.CharField(blank=True, default='---', max_length=50, null=True, verbose_name='№ курса (соответствующий классу в МООУ)'),
        ),
        migrations.AddField(
            model_name='childdata',
            name='udo_name',
            field=models.CharField(blank=True, default='---', max_length=50, verbose_name='Название УДО'),
        ),
        migrations.AddField(
            model_name='childdata',
            name='udo_status',
            field=models.CharField(blank=True, choices=[('Yes', 'Посещающий'), ('No', 'Домашний')], max_length=20, null=True, verbose_name='Посещение УДО'),
        ),
        migrations.AlterField(
            model_name='childdata',
            name='certificate_num',
            field=models.CharField(max_length=100, verbose_name='Номер сертификата'),
        ),
        migrations.AlterField(
            model_name='childdata',
            name='date_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='childdata',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='childdata',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='childdata',
            name='middle_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='childdata',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='childdata',
            name='sex',
            field=models.CharField(choices=[('boy', 'М'), ('girl', 'Ж')], default='Sex is not set', max_length=10, verbose_name='Пол'),
        ),
    ]
