# Generated by Django 3.1 on 2020-08-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs_app', '0009_auto_20200813_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdata',
            name='diagnose',
            field=models.TextField(blank=True, default='---', max_length=100, verbose_name='Диагноз (если выбран статус "ОВЗ" или "Инвалид"'),
        ),
    ]
