# Generated by Django 3.1 on 2020-08-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs_app', '0010_auto_20200813_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdata',
            name='municipal_status',
            field=models.CharField(blank=True, choices=[('not_avail', 'Не посещает'), ('Yes', 'Посещающий'), ('No', 'Семейное обучение')], default='not_avail', max_length=20, null=True, verbose_name='Посещение МООУ'),
        ),
    ]
