# Generated by Django 3.1 on 2020-08-17 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbs_app', '0012_auto_20200813_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childdata',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='Название группы')),
                ('group_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbs_app.section', verbose_name='Объединение')),
            ],
        ),
    ]
