# Generated by Django 3.1 on 2020-08-17 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbs_app', '0013_auto_20200817_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AddField(
            model_name='groups',
            name='teacher_set',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Педагоги', to='dbs_app.teacherdata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groups',
            name='teachers',
            field=models.ManyToManyField(related_name='Выбранные_педагоги', to='dbs_app.TeacherData'),
        ),
    ]
