# Generated by Django 3.1 on 2020-08-17 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbs_app', '0014_auto_20200817_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='teacher_set',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='teachers',
        ),
        migrations.AddField(
            model_name='groups',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Педагог', to='dbs_app.teacherdata'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AddingTeachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ope', models.ManyToManyField(to='dbs_app.Groups')),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dbs_app.teacherdata')),
            ],
        ),
    ]
