# Generated by Django 3.1 on 2020-08-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs_app', '0015_auto_20200817_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('available_in', models.ManyToManyField(to='dbs_app.TeacherData')),
            ],
        ),
        migrations.RemoveField(
            model_name='groups',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='AddingTeachers',
        ),
        migrations.AddField(
            model_name='groups',
            name='teacher',
            field=models.ManyToManyField(related_name='Педагог', to='dbs_app.Category'),
        ),
    ]
