# Generated by Django 3.1 on 2020-08-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs_app', '0017_auto_20200817_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='children',
            field=models.ManyToManyField(to='dbs_app.ChildData', verbose_name='Дети'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='teacher',
            field=models.ManyToManyField(to='dbs_app.TeacherData', verbose_name='Педагоги'),
        ),
    ]
